kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
metadata:
  name: fastapi-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 32334
    hostPort: 32334
    protocol: TCP
    listenAddress: "0.0.0.0"