apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 32334  # ← Manually set the NodePort
  selector:
    app: fastapi